version: "3.2"

networks: 
   frontend: 
   backend: 

services: 
   catalog: 
      build: 
         context: .\src\Services\ProductCatalogAPI
         dockerfile: Dockerfile 
      image: shoes/catalog
      environment: 
         - DatabaseServer=mssqlserver
         - DatabaseName=CatalogDb
         - DatabaseUser=sa
         - DatabasePassword=!IW2bac2821
      container_name: catalogapi
      ports: 
         - "5001:80"
      networks: 
         - backend
         - frontend
      depends_on: 
         - mssqlserver

   mssqlserver: 
      image: "microsoft/mssql-server-linux:latest"
      ports: 
         - "1445:1433"

      container_name: mssqlcontainer
      environment: 
         - ACCEPT_EULA=Y 
         - SA_PASSWORD=!IW2bac2821
      networks: 
         - backend